name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run version
        run: uname -a > ${{ github.workspace }}/release.txt

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArtifactRawWorks
          path: ${{ github.workspace }}/release.txt  # Fixed the file extension to ".txt"
